# Site settings
project_name: PROJECT
project_site: http://TODO_SITE
email: EMAIL@TODO
mailing_list: MAILINGLIST@TODO
mailing_list_archive: http://www.google.co.uk
issue_tracker: http://github.com/PROJECT/REPOSITORY/issues
issue_tracker_new_issue: http://github.com/PROJECT/REPOSITORY/issues/new
code_repository: http://github.com/PROJECT/CODE_REPOSITORY
doc_repository: http://github.com/PROJECT/DOC_REPOSITORY
copyright: 2014-2016, ORGANISATION. All rights reserved.

# gh-pages site subpath
baseurl: "/sample-site"

# Entries for menubar.
# title: caption used for item.
# url: relative path to HTML page.
menubar:
- title: Home
  url: /index.html
- title: Use
  url: /user/index.html
- title: Develop
  url: /developer/index.html
- title: Research
  url: /research/index.html
- title: Contribute
  url: /project/Contributing.html
- title: Get in Touch
  url: /project/HelpAndSupport.html
- title: Copyright and Licence
  url: /CopyrightLicence.html
- title: Site Map
  url: /SiteMap.html

# Build settings
highlighter: rouge
markdown: kramdown

gems:
  - jekyll-sitemap
